# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
