# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0002_auto_20200221_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='order_upload',
            field=models.ImageField(default='pics.jpg', upload_to='order_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to='Profile_pics'),
        ),
    ]
