# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0003_auto_20200224_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulist',
            options={'ordering': ['-order_name']},
        ),
    ]
