# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0004_auto_20200319_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulist',
            options={},
        ),
    ]
