# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-29 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlocator', '0005_auto_20200319_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
